export function defineGalaxy(monaco: typeof import("@/node_modules/monaco-editor/esm/vs/editor/editor.api")) {
    return monaco.editor.defineTheme("galaxy", {
        base: "vs-dark",
        inherit: true,
        rules: [
            { token: "comment", foreground: "5C7884" },
            { token: "keyword", foreground: "CC80FF" },
            { token: "string", foreground: "C8FF75" },
            { token: "string.escape", foreground: "8ADEFF" },
            { token: "number", foreground: "FF8A66" },
            { token: "operator", foreground: "8ADEFF" },
            { token: "delimiter", foreground: "8ADEFF" },
            { token: "identifier", foreground: "FF6169" },
            { token: "function", foreground: "80A8FF" },
            { token: "javascript", foreground: "FF6169" },
            { token: "type", foreground: "FFBF47" }
        ],
        colors: {
            "diffEditor.insertedLineBackground": "#22c55e30",
            "diffEditor.insertedTextBackground": "#22c55e70",
            "diffEditor.removedLineBackground": "#ef444430",
            "diffEditor.removedTextBackground": "#ef444470",
            "editor.background": "#020617",
            "editor.findMatchBackground": "#f8fafc30",
            "editor.findMatchBorder": "#f8fafc5a",
            "editor.findMatchHighlightBackground": "#f8fafc22",
            "editor.foreground": "#f8fafc",
            "editor.lineHighlightBackground": "#0f172a",
            "editor.inactiveSelectionBackground": "#1e293b",
            "editor.selectionBackground": "#334155",
            "editor.selectionHighlightBackground": "#3341551f",
            "editor.selectionHighlightBorder": "#3341553f",
            "editor.wordHighlightBackground": "#f8fafc2f",
            "editor.wordHighlightBorder": "#f8fafc3f",
            "editor.wordHighlightStrongBackground": "#10b9813f",
            "editor.wordHighlightStrongBorder": "#10b9817f",
            "editorCursor.foreground": "#f1f5f97f",
            "editorError.foreground": "#ef4444",
            "editorLineNumber.activeForeground": "#94a3b8",
            "editorLineNumber.foreground": "#475569",
            "editorMarkerNavigation.background": "#0f172a",
            "editorSuggestWidget.background": "#0f172a",
            "editorSuggestWidget.border": "#334155",
            "editorSuggestWidget.selectedBackground": "#1e293b",
            "editorWarning.foreground": "#eab308",
            "editorWidget.background": "#0f172a",
            "editorWidget.resizeBorder": "#10b981",
            "focusBorder": "#10b981",
            "input.background": "#020617",
            "input.foreground": "#f8fafc",
            "inputOption.activeBorder": "#10b981",
            "inputValidation.infoBorder": "#10b981",
            "list.activeSelectionBackground": "#1e293b",
            "list.focusBackground": "#ff0000",
            "list.hoverBackground": "#1e293b",
            "list.inactiveSelectionBackground": "#0f172a",
            "menu.background": "#0f172a",
            "menu.foreground": "#cbd5e1",
            "menu.separatorBackground": "#334155",
            "peekViewEditor.background": "#0f172a",
            "peekViewEditor.matchHighlightBackground": "#f8fafc22",
            "peekViewResult.background": "#1e293b",
            "scrollbar.shadow": "#020617",
            "scrollbarSlider.activeBackground": "#f8fafc3f",
            "scrollbarSlider.background": "#f8fafc1f",
            "scrollbarSlider.hoverBackground": "#f8fafc2f",
            "textBlockQuote.background": "#022c22",
            "textBlockQuote.border": "#10b981",
            "textLink.foreground": "#10b981"
        }
    });
}